### PR TITLE
inspect: remove format flag

### PR DESCRIPTION
**Pull request by hectorj2f**
Signed-off-by: Hector Fernandez <hector@chainguard.dev>

#### Summary

We didn't set any default format, so it is hard to know which options are available for the format.

#### Release Note

Fix: set default format value for the inspect' format flag.

### CODE REVIEW

**Comment by hectorj2f** [comment]
There is something else missing... pushing another commit

**Comment by hectorj2f** [comment]
`timestamp-cli inspect --timestamp_server http://localhost:5555 --timestamp response.tsr` I don't think we need to set the `--format` as a required flag, especially when there is a single option.

**Comment by hectorj2f** [comment]
ping @cpanato

**Comment by haydentherapper** [comment]
If we don’t have any other format supported, id just say to delete the flag.

**Comment by hectorj2f** [comment]
I wasn't sure, there were other plans for the format flag.

**Comment by hectorj2f** [comment]
If there aren't, then let's remove it.

**Comment by haydentherapper** [comment]
YAGNI, we can add it back later if we add more formatting options!

**Comment by hectorj2f** [comment]
@haydentherapper I removed the flag.

**Review by haydentherapper — APPROVED** [review]

**Pull request merged**
