### PR TITLE
Upload SLSA provenance to existing release

### PR DESCRIPTION
**Pull request by haydentherapper**
This changes the behavior of the provenance generator to not create a new release, since goreleaser already does. We add two steps to download the created provenance and upload it to the existing draft release.

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
we also can disable https://github.com/sigstore/timestamp-authority/blob/main/.goreleaser.yml#L95 then this part is not needed, but i am also fine with this

thanks!

**Comment by haydentherapper** [comment]
If we disable it in goreleaser, would the artifacts that are produced as part of it still be uploaded to the release created in the slsa provenance generator step? I wasn't sure, and someone pointed me to this approach. I'll try this, but happy to change it to either!

**Comment by haydentherapper** [comment]
Testing https://github.com/sigstore/timestamp-authority/actions/runs/3913966044

**Comment by haydentherapper** [comment]
Working as expected - Draft release is created, artifact is uploaded to the same tag

**Pull request merged**
